### PR TITLE
add math command description and fix typo

### PR DESCRIPTION
**Pull request by Infernum1**

### CODE REVIEW

**Comment by Elrynd** [comment]
If you wanna add French to your PR
```json
        "math": "`{0}math <problème>` *résout un problème de math",
```

**Comment by Infernum1** [comment]
gotta add it for other languages aswell

**Comment by Infernum1** [comment]
> If you wanna add French to your PR
> 
> ```json
>         "math": "`{0}math <problème>` *résout un problème de math",
> ```

but I guess I'll add this

**Review by Iapetus-11 — APPROVED** [review]
Thanks!

**Pull request merged**
