### PR TITLE
Changed gambling values

### PR DESCRIPTION
**Pull request by kaosj314**
This does not change any odds. It just makes the numbers feel like a real roll.

### CODE REVIEW

**Comment by XeDotCom** [comment]
actually, we are using two dice, so 2-12 is the correct range (1-1 to 6-6)

**Comment by Iapetus-11** [comment]
There are two dice. A normal dice can roll a maximum of 6. 6 + 6 == 12. In addition, the lowest a dice can roll is one, there being two dice makes the minimum possible sum 2.

**Comment by XeDotCom** [comment]
i said the same thing, didn't i :v

**Comment by Iapetus-11** [comment]
yes

**Comment by kaosj314** [comment]
In that case, I will make it so that it really rolls 2d6 instead of 1d11 + 1
Because the chances of rolling numbers in the middle are increased if it is 2d6

**Comment by Iapetus-11** [comment]
image
Perhaps you could use random.choices() with these weights, or maybe:
```py
u_roll = random.randint(1, 6) + random.randint(1, 6)
```

**Pull request closed without merging**
