### PR TITLE
Small factual corrections

### PR DESCRIPTION
**Pull request by XeDotCom**
+ Changed several questions' wording and answers to be more correct
line 542: https://twitter.com/Dinnerbone/status/558263033173389313
line 584: https://minecraft.fandom.com/wiki/Cat#Appearance
line 637: Grammar mistake
line 754: https://minecraft.fandom.com/wiki/Salmon#Drops
line 834-846: multiple answers for question; invalid
line 942: pumpkins cannot be worn

### CODE REVIEW

**Comment by Iapetus-11** [comment]
Please update all translations.

**Comment by Iapetus-11** [comment]
You also shouldn't have removed the pigs question, just changed one of the duplicate answers.

**Comment by Iapetus-11** [comment]
black and white cat should remain as is since people are more likely to refer to it as that instead of tuxedo.

**Comment by XeDotCom** [comment]
1) i have no idea how it's translated
2) alright
3) i did it because there is already a black cat

**Comment by Iapetus-11** [comment]
1. That's why we have translators
2. nice
3. black and white cat refers to a cat that is black AND white, not two cats that are black and white respectively...

**Comment by Iapetus-11** [comment]
I updated the main branch based off of some of the things you suggested here, thank you.

**Pull request closed without merging**
