### PR TITLE
Mining rework

### PR DESCRIPTION
**Pull request by Elrynd**
Please test this on VB GF first :d

### CODE REVIEW

**Comment by XeDotCom** [comment]
> 
> 
> Please test this on VB GF first :d

i agree, elrynd

**Comment by Iapetus-11** [comment]
> Please test this on VB GF first :d

I refuse

**Review by Iapetus-11 — APPROVED** [review]
I skimmed over it and it looks like it will work, I'll test on Villager Bot's GF I guess

**Comment by FGN-Inferno** [comment]
nice

**Pull request merged**
