### PR TITLE
Improve spanish lang

### PR DESCRIPTION
**Pull request by Chiruso**
Grammatical corrections and correct formmating to the spanish lang, including:
- Help menu
- Mention message (pingpong)
- Error messages
- Some fun commands

### CODE REVIEW

**Review by Iapetus-11 — COMMENTED** [review]
image
image

One of the existing Villager Bot translators suggested these changes, what do you think?

**Comment by Chiruso** [comment]
Yep. I think that "el de un usuario específico" sounds better 🙂

**Comment by Iapetus-11** [comment]
> Yep. I think that "el de un usuario específico" sounds better 🙂

Could you update your PR?

**Comment by Iapetus-11** [comment]
Closing as this PR is now out of date due to changes to the Spanish translation file.

**Pull request closed without merging**
