### PR TITLE
update inventory help text

### PR DESCRIPTION
**Pull request by quaackk**

### CODE REVIEW

**Comment by quaackk** [comment]
ehhhhhhh? is this ok ;-;

**Comment by Iapetus-11** [comment]
Not proper grammar

**Comment by Iapetus-11** [comment]
wait wrong pr my bad

**Review by Iapetus-11 — APPROVED** [review]

**Comment by quaackk** [comment]
breh.

**Comment by EarlyBirdIRL** [comment]
Lol

**Pull request merged**
