### PR TITLE
toilet paper is back in stock (also when you chug hoeny itll show you how much health you have)

### PR DESCRIPTION
**Pull request by gritor111**
git is pain.

### CODE REVIEW

**Comment by XeDotCom** [comment]
do we need to bring back toilet paper

**Comment by gritor111** [comment]
idk about you but i need toilet paper, also if you havent checked its 1/100k so itll still remain rare

**Comment by XeDotCom** [comment]
that feels like a personal agenda to me ngl

**Comment by gritor111** [comment]
¯\_(ツ)_/¯ i asked petus and he said yes

**Comment by XeDotCom** [comment]
if petus said yes, cool

not that i approve of your method of collecting tho

**Review by Iapetus-11 — CHANGES_REQUESTED** [review]
Update the text for the other languages. (Just put the English text there and the translators will translate later)

**Comment by XeDotCom** [comment]
also why isnt toilet paper sticky its the rarest item of the collection

**Comment by gritor111** [comment]
added text

**Pull request merged**
